language: go
go:
- 1.7.1
- master

install:
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2 ./..