language: go
go:
- 1.7.1
- master

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls

script:
  - ginkgo -r -tags=integartion --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --compilers=2 .
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN